### ISSUE TITLE
Unexpected Indent

### ISSUE THREAD

**Issue by Honowski** [panda0881/Instagram_data#2]
Good evening,
when i fill in the script with a user's name or a tag and run the script, i get this error:
:# python Instagram_Spider.py
  File "Instagram_Spider.py", line 65
    resp = self.s.get('http://instagram.com/explore/tags/' + tag_name)
    ^
IndentationError: unexpected indent

Any help?

**Comment by panda0881** [comment]
Hi, the indentation error typically comes from your coding habit. You may considering check your setting for the 'tab' in your IDE.

Besides, you may want to check this one out:
http://stackoverflow.com/questions/3920628/indentationerror-unexpected-indent-error

Hope it is helpful. If you have any other problem, I will try my best to help!

Hongming

**Comment by panda0881** [comment]
Hi, the indentation error typically comes from your coding habit. You may need to check your setting for the 'tab' in your IDE.

Besides, you may want to check this one out:
http://stackoverflow.com/questions/3920628/indentationerror-unexpected-indent-error

Hope it is helpful. If you have any other problem, I will try my best to help!

Hongming
