### ISSUE TITLE
Manual on setup and use

### ISSUE THREAD

**Issue by monajalal** [panda0881/Instagram_data#3]
Can you please provide instruction where to place this file or can you please upload the whole project? I assume I should replace this with spider.py in spider folder but got error. If you could provide help on this, would really appreciate

**Comment by panda0881** [comment]
Hi there, I'm not sure I clearly understand your problem. Actually you can put this py file anywhere you like and you can use import to import this file into your main algorithm file. Say you have a project folder called 'test_project', you can simply put this file under that folder and use `from Instagram_Spider import *` to import all the functions inside this file into your main algorithm file.

Btw, I saw you are from Madison. I exchanged in that school several years ago. It's a cool place.

Hongming
